#version: '3.8'

services:
  prophet:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ../../posts/mcmc:/app/mcmc:ro
    environment:
      - PYTHONUNBUFFERED=1
    container_name: prophet-jupyter
    restart: unless-stopped # Container will restart unless explicitly stopped
