baseURL = '/'
languageCode = 'en-us'
title = 'Dr. Codex Laborer'
theme = 'gokarna'
defaultContentLanguage = 'en'
enableEmoji = true
enableRobotsTXT = true
pygmentsStyle = 'monokai'

[params]
  description = 'Bayesian Data Codexer'
  footer = 'Â©DRC Lab'
  showBackToTopButton = true
  accentColor = '#682953ff'
  avatarURL = '/images/my-avatar.png'
  avatarSize = 'size-l'
  avatarAltText = 'DRC Lab logo'
  socialIcons = [
    {name = 'github', url = 'https://github.com/hublun'},
    {name = 'linkedin', url = 'https://www.linkedin.com/in/drclab'},
    {name = 'email', url = 'mailto:compute@dulun.com'}
  ]

[menu]
  [[menu.main]]
    name = 'C.J. Duan'
    pre = "<span data-feather='home'></span>"
    url = 'http://www.dulun.com'
    weight = 1

  [[menu.main]]
    name = 'Research Notes'
    pre = "<span data-feather='book'></span>"
    url = '/posts/'
    weight = 2

  [[menu.main]]
    name = 'Tags'
    pre = "<span data-feather='tag'></span>"
    url = '/tags/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
